apply plugin: 'com.android.test'
apply plugin: 'androidx.baselineprofile'

android {
    namespace = 'app.mpvnova.performance'
    compileSdk = 37
    targetProjectPath = ':app'

    defaultConfig {
        minSdk = 23
        targetSdk = 36
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
        testInstrumentationRunnerArguments['androidx.benchmark.suppressErrors'] = 'EMULATOR'
    }

    flavorDimensions += 'default'
    productFlavors {
        'default' {
            dimension = 'default'
        }
        api29 {
            dimension = 'default'
        }
    }

    buildTypes {
        benchmark {
            debuggable = false
        }
    }
}

baselineProfile {
    useConnectedDevices = true
}

dependencies {
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.5.0-rc01'
    implementation 'androidx.test.ext:junit:1.3.0'
    implementation 'androidx.test:runner:1.7.0'
    implementation 'androidx.test.uiautomator:uiautomator:2.4.0'
}
